### PR TITLE
add LICENSE file

### PR DESCRIPTION
**Pull request by mm318**
This PR is adding a __BSD 3-Clause__ LICENSE file. The choice of license comes from what's documented as the license on http://wiki.ros.org/joystick_drivers.

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
So, I don't think we can do this at the top-level.  If you look at https://github.com/ros2/joystick_drivers/blob/ros2/wiimote/package.xml, you'll see that the wiimote package is actually GPL, not BSD, so we can't relicense it here (all of the other packages in this repository are BSD).  If you want to add LICENSE files, then I think we'll need to do it in the individual subdirectories.

**Comment by mm318** [comment]
I see, I will update the pull request.

Then that also means that the Wiki page is inaccurate as well.

**Comment by clalancette** [comment]
> Then that also means that the Wiki page is inaccurate as well.

Not really, though it is subtle.  The `joystick_drivers` package is a meta-package that just depends on other packages; the "license" for that is BSD, though that is more of a formality than anything real since there is no code involved.  The dependent packages can have different licenses, and if you click on [wiimote](http://wiki.ros.org/wiimote?distro=melodic) it is indeed GPL.

**Comment by mm318** [comment]
Hi @clalancette, can you please review again? Thanks!

**Review by clalancette — APPROVED** [review]

**Pull request merged**
